### ISSUE TITLE
ToxAlert data

### ISSUE THREAD

**Issue by jonesse3** [openochem/openochem#3]
I'm working on comparing deep learning models that predict synergy of drug pairs for cancer treatment. Some of these published models use ToxAlert to obtain toxicophore info as input data for their models.
 
To reproduce and compare these models:
 
Is there a way to get all the negative matches in addition to the positive matches from the ToxAlert webserver?
How can I download all of the metadata (i.e., Name, SMARTS, endpoints, Alert IDs) for 3,248 alerts in a CSV/Excel file?

**Comment by openochem** [comment]
The data are inside of mysql database and thus can be retrieved from it. Just install OpenOchem, login to database and you can export all the data from SubstructureAlert table inside in ochem_demo database.

Still, I would recommend to use OCHEM to apply alerts, since it includes extended rules, which are not all covered by SMARTS.

**Comment by jonesse3** [comment]
Great thanks for the info!
